package com.hogwarts.repository;

import com.hogwarts.entity.HogwartsTestUser;
import com.hogwarts.entity.HogwartsTestUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HogwartsTestUserMapper {

    public HogwartsTestUser selectById(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hogwarts_test_user
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    int countByExample(HogwartsTestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hogwarts_test_user
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    int deleteByExample(HogwartsTestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hogwarts_test_user
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    int insert(HogwartsTestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hogwarts_test_user
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    int insertSelective(HogwartsTestUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hogwarts_test_user
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    List<HogwartsTestUser> selectByExample(HogwartsTestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hogwarts_test_user
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    int updateByExampleSelective(@Param("record") HogwartsTestUser record, @Param("example") HogwartsTestUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hogwarts_test_user
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    int updateByExample(@Param("record") HogwartsTestUser record, @Param("example") HogwartsTestUserExample example);
}