package com.hogwarts.entity;

import java.util.Date;

public class HogwartsTestUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.id
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.user_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.password
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.email
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.auto_create_case_job_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private String autoCreateCaseJobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.start_test_job_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private String startTestJobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.default_jenkins_id
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private Integer defaultJenkinsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.create_time
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hogwarts_test_user.update_time
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.id
     *
     * @return the value of hogwarts_test_user.id
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.id
     *
     * @param id the value for hogwarts_test_user.id
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.user_name
     *
     * @return the value of hogwarts_test_user.user_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.user_name
     *
     * @param userName the value for hogwarts_test_user.user_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.password
     *
     * @return the value of hogwarts_test_user.password
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.password
     *
     * @param password the value for hogwarts_test_user.password
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.email
     *
     * @return the value of hogwarts_test_user.email
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.email
     *
     * @param email the value for hogwarts_test_user.email
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.auto_create_case_job_name
     *
     * @return the value of hogwarts_test_user.auto_create_case_job_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public String getAutoCreateCaseJobName() {
        return autoCreateCaseJobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.auto_create_case_job_name
     *
     * @param autoCreateCaseJobName the value for hogwarts_test_user.auto_create_case_job_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setAutoCreateCaseJobName(String autoCreateCaseJobName) {
        this.autoCreateCaseJobName = autoCreateCaseJobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.start_test_job_name
     *
     * @return the value of hogwarts_test_user.start_test_job_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public String getStartTestJobName() {
        return startTestJobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.start_test_job_name
     *
     * @param startTestJobName the value for hogwarts_test_user.start_test_job_name
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setStartTestJobName(String startTestJobName) {
        this.startTestJobName = startTestJobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.default_jenkins_id
     *
     * @return the value of hogwarts_test_user.default_jenkins_id
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public Integer getDefaultJenkinsId() {
        return defaultJenkinsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.default_jenkins_id
     *
     * @param defaultJenkinsId the value for hogwarts_test_user.default_jenkins_id
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setDefaultJenkinsId(Integer defaultJenkinsId) {
        this.defaultJenkinsId = defaultJenkinsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.create_time
     *
     * @return the value of hogwarts_test_user.create_time
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.create_time
     *
     * @param createTime the value for hogwarts_test_user.create_time
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hogwarts_test_user.update_time
     *
     * @return the value of hogwarts_test_user.update_time
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hogwarts_test_user.update_time
     *
     * @param updateTime the value for hogwarts_test_user.update_time
     *
     * @mbggenerated Wed May 05 23:02:23 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}